wsl = false
no-multigrid = false
vsync = true
maximized = false
srgb = false
idle = true
neovim-bin = "/run/current-system/sw/bin/env nvim" # in reality found dynamically on $PATH if unset
frame = "full"
title-hidden = true
